### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by mikemhenry** [mikemhenry/sc2gameMapRepo#2]
I'd like to drop python 2 support, but since the OG repo has it, I should keep it.
If we support python 2, we need to test it, but I can't figure out why setup.py is blocking 2.7, see this [error](https://travis-ci.org/mikemhenry/sc2gameMapRepo/jobs/392068119)

**Comment by ttinies** [comment]
that's cute.  It could be a formatting issue.  Did you try it with a space?  [the docs](https://docs.python.org/2/distutils/setupscript.html#relationships-between-distributions-and-packages) seem to show multiple version strings with spaces separating the versions.

This isn't a significant issue. If this isn't easily solveable, I'm fine dropping python2 support and _maybe_ revisiting this when, um, we're bored.  _MAYBE_.

**Comment by mikemhenry** [comment]
From a principled stance, I'd like to drop python2 support to help move the world to python3. We can then use new python features that are not back ported, and if our package is so cool and helpful it causes someone to migrate to python3, I will be so happy.

But in the mean time, I got setup.py working with travis so now we are testing python2
